<?php

/**
 * @file
 * Main Wywisyg plugin module file.
 */
define("LEASINGCOM_PLACEHOLDER_PATTERN_INNER", 'wysiwyg_leasingcom-widget-embed_plugin');
define("LEASINGCOM_PLACEHOLDER_PATTERN", '<!--' . LEASINGCOM_PLACEHOLDER_PATTERN_INNER . '-->');

/**
 * Implements hook_wysiwyg_include_directory().
 */
function leasingcom_widget_wysiwyg_include_directory($type) {
  return $type;
}

/**
 * Implements hook_page_alter().
 */
function leasingcom_widget_page_alter(&$page) {
  drupal_add_css(drupal_get_path('module', 'leasingcom_widget') . '/plugins/leasingcom_widget_embed/leasingcom_widget_embed.css');
}

/**
 * Implements hook_node_view().
 */
function leasingcom_widget_node_view($node) {
  if (node_is_page($node)) {
    // @todo Do this in a better way using Dom.
    $leasing_markup = '<div id="leasingdotcom-best-deals" data-cid="0000" data-financeType="Personal" data-vehicleType="Car" [data-manufacturer] [data-manufacturer-ranges]></div>
<script type="text/javascript" src="https://demo-webapps.leasing.com/best-deals/load"></script>';
    $body = $node->content['body'][0]['#markup'];
    if (preg_match('/<!--leasingcom_widget_embed_plugin-(.*?)-->/', $body, $match) == 1) {
      $params = $match[1];
      $params = explode('-', $params);
      $params_array = array();
      foreach($params as $param) {
        $explode = explode(':', $param);
        $params_array[$explode[0]] = $explode[1];
      }
      // Data manufacturer.
      if ($params_array['data_manufacturer'] != 'undefined') {
        $leasing_markup = str_replace('[data-manufacturer]', 'data-manufacturer="' . $params_array['data_manufacturer'] . '"', $leasing_markup);
      }
      else {
        $leasing_markup = str_replace('[data-manufacturer]', '', $leasing_markup);
      }
      // Data manufacturer ranges
      if ($params_array['data_manufacturer_ranges'] != 'undefined') {
        $leasing_markup = str_replace('[data-manufacturer-ranges]', 'data-manufacturerRanges="' . $params_array['data_manufacturer_ranges'] . '"', $leasing_markup);
      }
      else {
        $leasing_markup = str_replace('[data-manufacturer-ranges]', '', $leasing_markup);
      }
      $full_comment = "<!--leasingcom_widget_embed_plugin-$match[1]-->";

      // Add leasing markup.
      $node->content['body'][0]['#markup'] = str_replace($full_comment, $leasing_markup, $node->content['body'][0]['#markup']);
    }
  }
}
